version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: new_blog
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
      - "8788:8788"
      - "8976:8976"
    stdin_open: true
    tty: true
